/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.view;
import model.Eclusa;
import controller.EclusaController;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author Pedro
 */
public class View extends javax.swing.JDialog {

    /**
     * Creates new form View
     */
    private Eclusa eclusa;
    private EclusaController controller;
    public View(EclusaController controller){
        this.controller=controller;
        initComponents();
    }
    public View(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public View(Eclusa eclusa){
        this.eclusa=eclusa;
        controller=new EclusaController(eclusa,this);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoAtualizarEclusa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        statusEclusa = new javax.swing.JLabel();
        BotaoPetroleiro = new javax.swing.JButton();
        botaoTurismo = new javax.swing.JButton();
        botaoBalsa = new javax.swing.JButton();
        filaEclusa = new javax.swing.JLabel();
        apurado = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        botaoCargueiro = new javax.swing.JButton();
        barraProgresso = new javax.swing.JProgressBar();
        encher = new javax.swing.JButton();
        secar = new javax.swing.JButton();
        sentEmbarcacao = new javax.swing.JLabel();
        tempoTotal = new javax.swing.JLabel();
        fechar = new javax.swing.JButton();
        abrir = new javax.swing.JButton();
        informacao = new javax.swing.JLabel();
        sentprox = new javax.swing.JLabel();
        embarcacaoeclusa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botaoCadastrarCapitao = new javax.swing.JButton();
        botaoAtualizarPrecos1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botaoAtualizarEclusa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoAtualizarEclusa.setText("Atualizar Eclusa");
        botaoAtualizarEclusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarEclusaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Simulador de Gestão de Eclusa");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Nova Embarcação:");

        statusEclusa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        statusEclusa.setText("Status da Eclusa: Seca");

        BotaoPetroleiro.setText("Petroleiro");
        BotaoPetroleiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPetroleiroActionPerformed(evt);
            }
        });

        botaoTurismo.setText("Turismo");
        botaoTurismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTurismoActionPerformed(evt);
            }
        });

        botaoBalsa.setText("Balsa");
        botaoBalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBalsaActionPerformed(evt);
            }
        });

        filaEclusa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filaEclusa.setText("Embarcações na fila: 0");

        apurado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apurado.setText("Total apurado no dia: R$0.00");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Sentido da Embarcação:");

        botaoCargueiro.setText("Cargueiro");
        botaoCargueiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCargueiroActionPerformed(evt);
            }
        });

        barraProgresso.setBackground(new java.awt.Color(255, 255, 255));
        barraProgresso.setStringPainted(true);

        encher.setText("Encher");
        encher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encherActionPerformed(evt);
            }
        });

        secar.setText("Secar");
        secar.setRequestFocusEnabled(false);
        secar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secarActionPerformed(evt);
            }
        });

        sentEmbarcacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sentEmbarcacao.setAlignmentX(5.0F);
        sentEmbarcacao.setAlignmentY(5.0F);

        tempoTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tempoTotal.setText("Previsao de tempo para todas as embarcações na fila: 0.0min");

        fechar.setText("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });

        informacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        informacao.setText("Eclusa Fechada");

        sentprox.setText("Sentido da próxima Embarcação: Fila vazia");

        embarcacaoeclusa.setText("Embarcaçao na Eclusa");
        embarcacaoeclusa.setActionCommand("EmbarcacaonaEclusa");
        embarcacaoeclusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embarcacaoeclusaActionPerformed(evt);
            }
        });

        jButton1.setText("Remover da Fila");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botaoCadastrarCapitao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoCadastrarCapitao.setText("Gerenciar Capitães");
        botaoCadastrarCapitao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarCapitaoActionPerformed(evt);
            }
        });

        botaoAtualizarPrecos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoAtualizarPrecos1.setText("Atualizar Preços");
        botaoAtualizarPrecos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarPrecos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(barraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(sentprox))
                                    .addComponent(informacao, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(abrir)
                                        .addGap(153, 153, 153)
                                        .addComponent(fechar))
                                    .addComponent(statusEclusa)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoCargueiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotaoPetroleiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoTurismo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoBalsa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(filaEclusa)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton1))
                                    .addComponent(tempoTotal)
                                    .addComponent(apurado)
                                    .addComponent(embarcacaoeclusa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(encher)
                                        .addGap(127, 127, 127)
                                        .addComponent(secar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(botaoAtualizarEclusa, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botaoCadastrarCapitao, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botaoAtualizarPrecos1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(35, 35, 35)
                                .addComponent(sentEmbarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(botaoTurismo)
                            .addComponent(botaoBalsa)
                            .addComponent(botaoCargueiro)
                            .addComponent(BotaoPetroleiro))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filaEclusa)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(tempoTotal)
                        .addGap(18, 18, 18)
                        .addComponent(apurado)
                        .addGap(18, 18, 18)
                        .addComponent(embarcacaoeclusa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoAtualizarPrecos1)
                        .addGap(35, 35, 35)
                        .addComponent(botaoCadastrarCapitao)
                        .addGap(34, 34, 34)
                        .addComponent(botaoAtualizarEclusa)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(sentEmbarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sentprox)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(statusEclusa)))
                .addGap(17, 17, 17)
                .addComponent(barraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encher)
                    .addComponent(secar)
                    .addComponent(fechar)
                    .addComponent(abrir))
                .addGap(18, 18, 18)
                .addComponent(informacao)
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAtualizarEclusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarEclusaActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_botaoAtualizarEclusaActionPerformed
    
    public void mostrarErro(){
        JOptionPane.showMessageDialog(this, "Por favor, insira valores numéricos válidos.");
    }
    private void botaoCargueiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCargueiroActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_botaoCargueiroActionPerformed

    private void BotaoPetroleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPetroleiroActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_BotaoPetroleiroActionPerformed

    private void encherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encherActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_encherActionPerformed

    private void botaoTurismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTurismoActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_botaoTurismoActionPerformed

    private void botaoBalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBalsaActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_botaoBalsaActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_abrirActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_fecharActionPerformed

    private void secarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secarActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_secarActionPerformed

    private void embarcacaoeclusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embarcacaoeclusaActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_embarcacaoeclusaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.evento(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoCadastrarCapitaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarCapitaoActionPerformed
        controller.evento(evt);// TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarCapitaoActionPerformed

    private void botaoAtualizarPrecos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarPrecos1ActionPerformed
        controller.evento(evt);// TODO add your handling code here:
    }//GEN-LAST:event_botaoAtualizarPrecos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View dialog = new View(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoPetroleiro;
    private javax.swing.JButton abrir;
    private javax.swing.JLabel apurado;
    private javax.swing.JProgressBar barraProgresso;
    private javax.swing.JButton botaoAtualizarEclusa;
    private javax.swing.JButton botaoAtualizarPrecos1;
    private javax.swing.JButton botaoBalsa;
    private javax.swing.JButton botaoCadastrarCapitao;
    private javax.swing.JButton botaoCargueiro;
    private javax.swing.JButton botaoTurismo;
    private javax.swing.JButton embarcacaoeclusa;
    private javax.swing.JButton encher;
    private javax.swing.JButton fechar;
    private javax.swing.JLabel filaEclusa;
    private javax.swing.JLabel informacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JButton secar;
    private javax.swing.JLabel sentEmbarcacao;
    private javax.swing.JLabel sentprox;
    private javax.swing.JLabel statusEclusa;
    private javax.swing.JLabel tempoTotal;
    // End of variables declaration//GEN-END:variables

    public void atualizaFila(int tamanho,float tempo){
        filaEclusa.setText("Embarcações na fila: "+tamanho);
        tempoTotal.setText("Previsao de tempo para todas as embarcações na fila: "+ tamanho*tempo+"min");
    }
    public void atualizartotalApurado(){
        apurado.setText("Total apurado no dia: R$"+eclusa.totalApuradoDia());
    }
    public void atualizartotalApuradoRemove(){
        apurado.setText("Total apurado no dia: R$"+eclusa.removerDaFila(eclusa.tamanhoFila()-1));
    }
    public void recado(String recado){
        informacao.setText(recado);
    }
    public void status(String status){
        statusEclusa.setText("Status da Eclusa: "+status);
    }
    public void sentido(String sentido){
        sentEmbarcacao.setText(sentido);
    }
    public void sentidoProxima(String sentido){
        sentprox.setText("Sentido da próxima Embarcação: "+sentido);
    }
    public void barra(int valor){
        barraProgresso.setValue(valor);
    }
         
}
